### ISSUE TITLE
MakeFille Error

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [jichu4n/prc-tools-remix#22]
Hey Yall, so anyways when i type make in the terminal to compile a prc file, it gives me a error. The error says:buildtools/toolchain/bin//m68k-none-elf-gcc -o code0001.elf  -Wsign-compare -Wextra -Wall -Werror -Wno-unused-parameter -Wno-old-style-declaration -Wno-unused-function -Wno-unused-variable -Wno-error=cpp -Wno-error=switch -Wno-multichar -funsafe-math-optimizations -Os -m68000 -mno-align-int -mpcrel -fpic -fshort-enums -mshort -Wl,--gc-sections -Wl,-T linker.lkr main.cpp
make: buildtools/toolchain/bin//m68k-none-elf-gcc: No such file or directory
make: *** [Makefile:39: code0001.elf] Error 127

idk what to do so can you help me please

**Comment by gingerbeardman** [comment]
you are missing the build tools at the expected location:

> buildtools/toolchain/bin//m68k-none-elf-gcc

did you follow the readme for setup?

**Comment by NeoGeoFreak2004** [comment]
now the terminal is telling me this:uildtools/toolchain/bin//m68k-none-elf-gcc/m68k-none-elf-gcc -o code0001.elf  -Wsign-compare -Wextra -Wall -Werror -Wno-unused-parameter -Wno-old-style-declaration -Wno-unused-function -Wno-unused-variable -Wno-error=cpp -Wno-error=switch -Wno-multichar -funsafe-math-optimizations -Os -m68000 -mno-align-int -mpcrel -fpic -fshort-enums -mshort -Wl,--gc-sections -Wl,-T linker.lkr main.cpp
make: buildtools/toolchain/bin//m68k-none-elf-gcc/m68k-none-elf-gcc: No such file or directory
make: *** [Makefile:39: code0001.elf] Error 127
so how do i fix this?

**Comment by gingerbeardman** [comment]
it's the same error.

- did you follow the readme for setup? 
- which platform are you running on?

**Comment by NeoGeoFreak2004** [comment]
Yes, I followed the readme for setup and the platform I am running on is Windows 11 with WSL.
